org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.extra.enableAndroidLocationsBuildService=false
android.overridePathCheck=true
android.suppressUnsupportedCompileSdk=34
kotlin.code.style=official
systemProp.android.user.home=D:\\MCA Subjects\\MAD Lab\\Experiment 07\\.android_home
